export enum SecretsKeys {
  MONDAY_SIGNING_SECRET = 'MONDAY_SIGNING_SECRET',
  MONDAY_OAUTH_CLIENT_SECRET = 'MONDAY_OAUTH_CLIENT_SECRET',
}

export enum EnvironmentsKeys {
  MONDAY_OAUTH_CLIENT_ID = 'MONDAY_OAUTH_CLIENT_ID',
  MONDAY_OAUTH_TOKEN_PATH = 'MONDAY_OAUTH_TOKEN_PATH',
  MONDAY_OAUTH_BASE_PATH = 'MONDAY_OAUTH_BASE_PATH',
}
